#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SHELL EXTENSIONS]${normal}"
echo "${bold}[Updating powerlevel10k]${normal}"
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
echo "${bold}[Updating zsh-autosuggestions]${normal}"
git -C ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull
echo "${bold}[Updating CONFIGS]${normal}"
echo "${bold}[Updating aria2]${normal}"
mkdir -p ~/.config/aria2
curl https://raw.githubusercontent.com/voltamage/common/master/.config/aria2/aria2.conf > ~/.config/aria2/aria2.conf -#
echo "${bold}[Updating neofetch]${normal}"
mkdir -p ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/common/master/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#
echo "${bold}[Updating SCRIPTS]${normal}"
echo "${bold}[Updating brsync]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/brsync > ~/scripts/brsync -#
sudo chmod u+x ~/scripts/brsync
echo "${bold}[Updating fnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
echo "${bold}[Updating maintain]${normal}"
curl https://raw.githubusercontent.com/voltamage/proxmox/master/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
echo "${bold}[Updating mfnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
echo "${bold}[Updating nonag]${normal}"
curl https://raw.githubusercontent.com/voltamage/proxmox/master/scripts/nonag > ~/scripts/nonag -#
sudo chmod u+x ~/scripts/nonag
echo "${bold}[Updating ALIASES]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#
curl https://raw.githubusercontent.com/voltamage/proxmox/master/.oh-my-zsh/custom/proxmox.zsh > ~/.oh-my-zsh/custom/proxmox.zsh -#
echo "${bold}[Updating PKGLIST]${normal}"
comm -12 <(grep 'sudo apt-get install' ~/.zsh_history | sed '/|/d' | awk '{$1=$2=$3=$4=""; print $0}' | sed s/\\s/\\n/g | sort -n) <(dpkg --list | awk '{print $2}' | sed 's/:amd64//' | sort -n) | sed '/^$/d' > ~/.pkglist

echo ""
echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning junk directories]${normal}"
sudo rm /root/.bash_history
sudo rm /root/.lesshst
sudo rm /root/.wget-hsts
rm ~/.bash_history
rm ~/.lesshst
rm ~/.wget-hsts
/home/$USER/scripts/rmshit.py

echo ""
echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart

echo ""
echo "${bold}[DONE]${normal}"
exec zsh
